#!/bin/bash -e

OUTPUT_DIR="$PWD/output/acceptance"

rm -f "$OUTPUT_DIR/*.xml"

pwd
ls -la

echo "Running acceptance tests"
docker build --pull -t summon-acceptance -f Dockerfile.acceptance .

docker run --rm -t \
           -v "$OUTPUT_DIR:/summon/acceptance/output" \
           summon-acceptance bash -c 'cucumber --format junit --out ./output'

echo "Results are in $OUTPUT_DIR"
